In [1]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv("/skin clinic campaign.csv")
df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign
0,100001,Female,30-50,Yes,9,Yes
1,100002,Male,>50,Yes,15,No
2,100003,Male,>50,Yes,11,No
3,100004,Female,30-50,No,6,No
4,100005,Female,<30,Yes,13,Yes

In [5]:
df["Response"] = df["Response_to_Campaign"].map({
    "Yes": 1,
    "No": 0
})

In [6]:
df.head()

,CustID,Gender,AgeGroup,Purchase_Last_Quarter,Unique_Products_Purchased,Response_to_Campaign,Response
0,100001,Female,30-50,Yes,9,Yes,1
1,100002,Male,>50,Yes,15,No,0
2,100003,Male,>50,Yes,11,No,0
3,100004,Female,30-50,No,6,No,0
4,100005,Female,<30,Yes,13,Yes,1

Gender vs Campaign Response

In [7]:
gender_response = (
    df.groupby("Gender")["Response"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

gender_response.columns = [
    "Gender",
    "Response Rate (%)"
]

gender_response

   Gender  Response Rate (%)
0  Female              43.77
1    Male              34.08

Age Group vs Campaign Response

In [10]:
age_group_response = (
    df.groupby("AgeGroup")["Response"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)
age_group_response.columns = [
    "Age Group",
    "Response Rate (%)"
]
age_group_response

  Age Group  Response Rate (%)
0     30-50              47.06
1       <30              32.93
2       >50              32.60

Purchase in Last Quarter vs Campaign Response

In [11]:
purchase_response = (
    df.groupby("Purchase_Last_Quarter")["Response"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

purchase_response.columns = [
    "Purchased Last Quarter",
    "Response Rate (%)"
]

purchase_response

  Purchased Last Quarter  Response Rate (%)
0                     No              21.69
1                    Yes              49.65

Product Usage vs Campaign Response

In [13]:
df["Product_Usage"] = pd.cut(
    df["Unique_Products_Purchased"],
    bins=[0, 4, 8, np.inf],
    labels=["1-4", "5-8", ">8"]
)

In [17]:
product_response = (
    df.groupby(
        "product_Usage",
        observed=False
    )["Response"]
    .mean()
    .mul(100)
    .round(2)
    .reset_index()
)

product_response.columns = [
    "Product Usage",
    "Response Rate (%)"
]

product_response

  Product Usage  Response Rate (%)
0           1-4              18.08
1           5-8              38.48
2            >8              52.00